# Generated by Django 5.2.16 on 2026-09-11 08:06

import apps.sms.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ghasedak', 'قاصدک'), ('sms_ir', 'sms.ir')], max_length=20, unique=True, verbose_name='ارائه\u200cدهنده')),
                ('provider_display', models.CharField(blank=True, max_length=50, verbose_name='نام نمایشی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_configured', models.BooleanField(default=False, verbose_name='تنظیم شده')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='کلید API')),
                ('line_number', models.CharField(blank=True, max_length=30, verbose_name='شماره خط')),
                ('send_method', models.CharField(choices=[('single', 'ارسال تکی (بدون قالب)'), ('otp', 'ارسال با قالب (OTP)')], default='otp', max_length=20, verbose_name='روش ارسال پیش\u200cفرض')),
                ('credit', models.IntegerField(blank=True, null=True, verbose_name='اعتبار (ریال)')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بررسی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک',
                'verbose_name_plural': 'تنظیمات پیامک',
                'db_table': 'sms_provider_config',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=50, unique=True, verbose_name='کلید رویداد')),
                ('event_name', models.CharField(max_length=100, verbose_name='نام رویداد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('ghasedak_template', models.CharField(blank=True, max_length=100, verbose_name='نام قالب قاصدک')),
                ('ghasedak_params', models.JSONField(blank=True, default=list, verbose_name='پارامترهای قاصدک')),
                ('smsir_template_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه قالب sms.ir')),
                ('smsir_params', models.JSONField(blank=True, default=list, verbose_name='پارامترهای sms.ir')),
                ('single_message', models.TextField(blank=True, verbose_name='متن تکی')),
                ('single_params', models.JSONField(blank=True, default=list, verbose_name='پارامترهای متن تکی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_system', models.BooleanField(default=False, verbose_name='قالب سیستمی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'قالب پیامک',
                'verbose_name_plural': 'قالب\u200cهای پیامک',
                'db_table': 'sms_template',
                'ordering': ['event_key'],
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ghasedak', 'قاصدک'), ('sms_ir', 'sms.ir')], max_length=20, verbose_name='ارائه\u200cدهنده')),
                ('send_method', models.CharField(choices=[('single', 'تکی'), ('otp', 'OTP')], default='otp', max_length=20, verbose_name='روش ارسال')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='شماره گیرنده')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('template_name', models.CharField(blank=True, max_length=100, verbose_name='نام قالب')),
                ('event_key', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='کلید رویداد')),
                ('priority', models.CharField(choices=[('normal', 'عادی'), ('high', 'بالا'), ('critical', 'بحرانی')], default='normal', max_length=20, verbose_name='اولویت')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='هشدار ارسال شد')),
                ('alert_sent_via', models.CharField(blank=True, max_length=20, null=True, verbose_name='هشدار از طریق')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شناسه در provider')),
                ('pack_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه مجموعه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شده'), ('delivered', 'تحویل شده'), ('failed', 'ناموفق'), ('blacklist', 'لیست سیاه'), ('unknown', 'نامشخص')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('error_code', models.IntegerField(blank=True, null=True, verbose_name='کد خطا')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='هزینه (ریال)')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='پاسخ خام provider')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='نوع شیء مرتبط')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه شیء مرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بررسی وضعیت')),
                ('user', apps.sms.fields.IntForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام ارسالی',
                'verbose_name_plural': 'پیام\u200cهای ارسالی',
                'db_table': 'sms_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ghasedak', 'قاصدک'), ('sms_ir', 'sms.ir')], max_length=20, verbose_name='ارائه\u200cدهنده')),
                ('error_type', models.CharField(choices=[('api_error', 'خطای API'), ('network_error', 'خطای شبکه'), ('credit_low', 'کمبود اعتبار'), ('config_error', 'خطای تنظیمات'), ('template_error', 'خطای قالب'), ('auth_error', 'خطای احراز هویت'), ('rate_limit', 'محدودیت نرخ'), ('unknown', 'نامشخص')], default='unknown', max_length=50, verbose_name='نوع خطا')),
                ('error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد خطا')),
                ('error_message', models.TextField(verbose_name='پیام خطا')),
                ('severity', models.CharField(choices=[('low', 'پایین'), ('medium', 'متوسط'), ('high', 'بالا'), ('critical', 'بحرانی')], default='medium', max_length=20, verbose_name='شدت')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='برطرف شده')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان برطرف')),
                ('resolution_note', models.TextField(blank=True, verbose_name='یادداشت برطرف\u200cسازی')),
                ('admin_notified', models.BooleanField(default=False, verbose_name='اطلاع به ادمین')),
                ('admin_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اطلاع')),
                ('notified_via_provider', models.CharField(blank=True, max_length=20, null=True, verbose_name='اطلاع از طریق')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('resolved_by', apps.sms.fields.IntForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sms_errors', to=settings.AUTH_USER_MODEL, verbose_name='برطرف\u200cکننده')),
                ('sms_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='sms.smsmessage', verbose_name='پیام مرتبط')),
            ],
            options={
                'verbose_name': 'خطای پیامک',
                'verbose_name_plural': 'خطاهای پیامک',
                'db_table': 'sms_error_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ghasedak', 'قاصدک'), ('sms_ir', 'sms.ir')], max_length=20, verbose_name='ارائه\u200cدهنده')),
                ('line_number', models.CharField(blank=True, max_length=30, verbose_name='خط اختصاصی')),
                ('from_number', models.CharField(db_index=True, max_length=20, verbose_name='شماره فرستنده')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('external_id', models.CharField(max_length=100, verbose_name='شناسه یکتا در provider')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده')),
                ('is_flagged', models.BooleanField(db_index=True, default=False, verbose_name='علامت\u200cگذاری')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='زمان دریافت')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='داده خام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', apps.sms.fields.IntForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_inbox', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط')),
            ],
            options={
                'verbose_name': 'پیام دریافتی',
                'verbose_name_plural': 'پیام\u200cهای دریافتی',
                'db_table': 'sms_inbox',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_external_id')],
            },
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['provider', 'status'], name='sms_message_provide_25ac89_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['user'], name='sms_message_user_id_9304c3_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='sms_message_related_77bbd9_idx'),
        ),
        migrations.AddIndex(
            model_name='smserrorlog',
            index=models.Index(fields=['provider', 'created_at'], name='sms_error_l_provide_4b36cc_idx'),
        ),
        migrations.AddIndex(
            model_name='smserrorlog',
            index=models.Index(fields=['severity'], name='sms_error_l_severit_e2a55c_idx'),
        ),
        migrations.AddIndex(
            model_name='smserrorlog',
            index=models.Index(fields=['error_type'], name='sms_error_l_error_t_924242_idx'),
        ),
        migrations.AddIndex(
            model_name='smserrorlog',
            index=models.Index(fields=['is_resolved'], name='sms_error_l_is_reso_5bbf3b_idx'),
        ),
    ]
