# Generated by Django 5.2.16 on 2026-09-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='send_method',
            field=models.CharField(choices=[('single', 'ارسال تکی (متن ساده)'), ('otp', 'ارسال OTP (با قالب provider)')], default='single', help_text='single: متن ساده | otp: قالب provider', max_length=20, verbose_name='نوع ارسال'),
        ),
    ]
