# Generated by Django 5.2.16 on 2026-08-20 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api', 'API همگام\u200cسازی'), ('csv', 'آپلود CSV')], default='csv', max_length=50, verbose_name='منبع')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='نام فایل')),
                ('file_size', models.IntegerField(default=0, verbose_name='حجم فایل (بایت)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل\u200cشده'), ('failed', 'خطا')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('trades_imported', models.IntegerField(default=0, verbose_name='تعداد تریدهای واردشده')),
                ('trades_skipped', models.IntegerField(default=0, verbose_name='تعداد تریدهای تکراری')),
                ('errors', models.JSONField(default=list, verbose_name='خطاها')),
                ('warnings', models.JSONField(default=list, verbose_name='هشدارها')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ واردات',
                'verbose_name_plural': 'لاگ\u200cهای واردات',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='import_impo_user_id_de054c_idx'), models.Index(fields=['user', 'status'], name='import_impo_user_id_172112_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(blank=True, help_text='نام کارگزاری که این mapping برای آن ذخیره شده (مثلاً MetaTrader 4)', max_length=100, verbose_name='نام کارگزار')),
                ('column_mapping', models.JSONField(default=dict, help_text='دیکشنری نگاشت: {"filed_model": "نام_ستون_در_CSV"}', verbose_name='نگاشت ستون\u200cها')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_mappings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نگاشت CSV',
                'verbose_name_plural': 'نگاشت\u200cهای CSV',
                'ordering': ['-is_default', 'broker_name'],
                'indexes': [models.Index(fields=['user', 'broker_name'], name='import_impo_user_id_d41492_idx'), models.Index(fields=['user', 'is_default'], name='import_impo_user_id_f68c2a_idx')],
                'unique_together': {('user', 'broker_name')},
            },
        ),
    ]
