version: '3'
services:
  # سرویس MySQL
  mysql:
    image: mysql:8.0
    container_name: trade_journal_mysql
    restart: always
    environment:
      MYSQL_DATABASE: trading_journal
      MYSQL_ROOT_PASSWORD: po879000
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup:/backup
    networks:
      - trade_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=production
      - DB_NAME=trading_journal
      - DB_USER=root
      - DB_PASSWORD=po879000
      - DB_HOST=mysql
      - DB_PORT=3306
      - REDIS_HOST=redis
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,213.108.241.154,c648c6e04a1a
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://213.108.241.154:3000
    networks:
      - trade_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - trade_network

  redis:
    image: redis:7.2-alpine
    container_name: trade_journal_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trade_network

  celery_worker:
    build: ./backend
    container_name: trade_journal_celery
    command: celery -A trading_journal worker --loglevel=info
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      - DB_NAME=trading_journal
      - DB_USER=root
      - DB_PASSWORD=po879000
      - DB_HOST=mysql
      - REDIS_HOST=redis
    networks:
      - trade_network

  celery_beat:
    build: ./backend
    container_name: trade_journal_celery_beat
    command: celery -A trading_journal beat --loglevel=info
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      - DB_NAME=trading_journal
      - DB_USER=root
      - DB_PASSWORD=po879000
      - DB_HOST=mysql
      - REDIS_HOST=redis
    networks:
      - trade_network

volumes:
  mysql_data:
  redis_data:

networks:
  trade_network: