# Generated by Django 5.2.16 on 2026-08-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconsultation',
            name='comparison_stats',
            field=models.JSONField(blank=True, default=dict, help_text='آمار مقایسه با تریدهای مشابه', null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='risk_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='درصد ریسک از کل سرمایه', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='session_type',
            field=models.CharField(blank=True, choices=[('High Pro', 'حرفه\u200cای'), ('Low Pro', 'مبتدی')], help_text='نوع جلسه معاملاتی', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='strategy_type',
            field=models.CharField(blank=True, choices=[('LTP', 'LTP'), ('ITP', 'ITP'), ('STP', 'STP')], help_text='نوع استراتژی', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='timeframes',
            field=models.CharField(blank=True, help_text='تایم\u200cفریم\u200cهای استفاده\u200cشده (مثلاً: D1, H4, H1)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='حجم معامله (لات)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='ai_response',
            field=models.JSONField(default=dict, help_text='تحلیل کامل AI شامل strengths, warnings, suggestion, tip, psychology'),
        ),
    ]
