# Generated by Django 5.2.16 on 2026-08-10 19:01

import apps.trading.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_aiconsultation_comparison_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='تصویر چارت معامله (حداکثر ۵ مگابایت)', max_length=500, null=True, upload_to=apps.trading.models.screenshot_upload_path, verbose_name='تصویر چارت'),
        ),
    ]
