# Generated by Django 5.2.16 on 2026-08-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_trade_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconsultation',
            name='model_used',
            field=models.CharField(blank=True, help_text='نام مدل هوش مصنوعی استفاده\u200cشده (مثلاً llama3.1:8b)', max_length=50, null=True),
        ),
    ]
