# Generated by Django 5.2.16 on 2026-08-11 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_aiconsultation_model_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconsultation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'خطا')], default='pending', help_text='وضعیت پردازش مشاوره', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='ai_response',
            field=models.JSONField(default=dict, help_text='تحلیل کامل AI'),
        ),
        migrations.AddIndex(
            model_name='aiconsultation',
            index=models.Index(fields=['status'], name='trading_ai__status_d479b4_idx'),
        ),
    ]
