# Generated by Django 5.2.16 on 2026-08-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_aiconsultation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconsultation',
            name='internal_analytics',
            field=models.JSONField(blank=True, default=dict, help_text='تحلیل داخلی تاریخچه کاربر (نرخ برد، سود کل، بهترین استراتژی و ...)', null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='live_price',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='قیمت لحظه\u200cای هنگام مشاوره', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='price_diff_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='درصد تفاوت قیمت ورود با قیمت لحظه\u200cای', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='price_warning',
            field=models.TextField(blank=True, help_text='هشدار تفاوت قیمت ورود با قیمت لحظه\u200cای', null=True),
        ),
    ]
