# Generated by Django 5.2.16 on 2026-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_aiconsultation_internal_analytics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconsultation',
            name='price_diff_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='درصد تفاوت قیمت ورود با قیمت لحظه\u200cای', max_digits=10, null=True),
        ),
    ]
