# Generated by Django 5.2.16 on 2026-08-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_portfolio_trade_portfolio_tradingrule_portfolio_and_more'),
    ]

    operations = [
    ]
