# Generated by Django 5.2.16 on 2026-08-19 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_add_discipline_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_trades_per_day', models.IntegerField(default=5, help_text='تعداد تریدهای مجاز در هر روز', verbose_name='حداکثر ترید در روز')),
                ('daily_loss_limit', models.DecimalField(decimal_places=2, default=500.0, help_text='حداکثر ضرر مجاز در روز', max_digits=10, verbose_name='سقف ضرر روزانه (دلار)')),
                ('max_loss_per_trade', models.DecimalField(decimal_places=2, default=100.0, help_text='حداکثر ضرر مجاز برای هر ترید (هشدار)', max_digits=10, verbose_name='سقف ضرر هر ترید (دلار)')),
                ('max_contract_size', models.DecimalField(decimal_places=2, default=2.0, help_text='حداکثر حجم مجاز برای هر ترید (هشدار)', max_digits=10, verbose_name='حداکثر حجم هر ترید (لات)')),
                ('cooldown_consecutive_losses', models.IntegerField(default=2, help_text='پس از چند ضرر متوالی، کول\u200cداون فعال شود', verbose_name='تعداد ضرر متوالی برای کول\u200cداون')),
                ('cooldown_duration_minutes', models.IntegerField(default=15, help_text='مدت زمان قفل شدن معاملات', verbose_name='مدت کول\u200cداون (دقیقه)')),
                ('cooldown_after_daily_loss', models.BooleanField(default=True, help_text='آیا پس از رسیدن به سقف ضرر روزانه، تا پایان روز قفل شود؟', verbose_name='کول\u200cداون پس از سقف ضرر روزانه')),
                ('cooldown_after_max_trades', models.BooleanField(default=True, help_text='آیا پس از رسیدن به سقف ترید روزانه، تا پایان روز قفل شود؟', verbose_name='کول\u200cداون پس از سقف ترید')),
                ('manual_cooldown_minutes', models.IntegerField(default=0, help_text='مدت زمان کول\u200cداون دستی (۰ = غیرفعال)', verbose_name='کول\u200cداون اختیاری (دقیقه)')),
                ('pre_trade_checklist_items', models.JSONField(default=list, help_text='لیست آیتم\u200cهایی که کاربر باید قبل از ورود تیک بزند', verbose_name='آیتم\u200cهای چک\u200cلیست')),
                ('checklist_required', models.BooleanField(default=True, help_text='آیا تکمیل چک\u200cلیست برای ثبت ترید الزامی است؟', verbose_name='چک\u200cلیست اجباری')),
                ('daily_habits', models.JSONField(default=list, help_text='لیست عادت\u200cهایی که کاربر باید روزانه تکمیل کند', verbose_name='عادات روزانه')),
                ('tiltmeter_weights', models.JSONField(default=dict, help_text='وزن\u200cهای هر بخش برای محاسبه Tiltmeter', verbose_name='وزن\u200cهای Tiltmeter')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_settings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات انضباطی',
                'verbose_name_plural': 'تنظیمات انضباطی',
                'db_table': 'trading_discipline_settings',
            },
        ),
        migrations.CreateModel(
            name='DailyDisciplineState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('trades_today', models.IntegerField(default=0, verbose_name='تعداد ترید امروز')),
                ('daily_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ضرر امروز')),
                ('consecutive_losses', models.IntegerField(default=0, verbose_name='ضرر متوالی')),
                ('is_locked_until_end_of_day', models.BooleanField(default=False, verbose_name='قفل تا پایان روز')),
                ('is_cooldown_active', models.BooleanField(default=False, verbose_name='کول\u200cداون فعال')),
                ('cooldown_until', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان کول\u200cداون')),
                ('cooldown_reason', models.CharField(blank=True, max_length=100, verbose_name='دلیل کول\u200cداون')),
                ('tiltmeter_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='امتیاز Tiltmeter')),
                ('compliance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ پایبندی')),
                ('habits_completed', models.JSONField(default=list, verbose_name='عادات تکمیل\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_discipline_states', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وضعیت روزانه انضباط',
                'verbose_name_plural': 'وضعیت\u200cهای روزانه انضباط',
                'db_table': 'trading_daily_discipline_state',
                'indexes': [models.Index(fields=['user', 'date'], name='trading_dai_user_id_ef48bb_idx'), models.Index(fields=['user', 'is_cooldown_active'], name='trading_dai_user_id_598cf8_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_name', models.CharField(max_length=100, verbose_name='نام عادت')),
                ('habit_description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شد')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_habits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عادت روزانه',
                'verbose_name_plural': 'عادات روزانه',
                'db_table': 'trading_daily_habit',
                'indexes': [models.Index(fields=['user', 'date'], name='trading_dai_user_id_85cd9b_idx')],
                'unique_together': {('user', 'habit_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DisciplineViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('max_trades', 'بیش\u200cترید'), ('daily_loss', 'سقف ضرر روزانه'), ('consecutive_loss', 'ضرر متوالی'), ('max_loss_per_trade', 'سقف ضرر هر ترید'), ('max_contract_size', 'حجم بیش از حد'), ('checklist_missing', 'چک\u200cلیست تکمیل نشده'), ('over_trade', 'اورترید'), ('emotional_trade', 'معامله احساسی'), ('other', 'سایر')], max_length=30, verbose_name='نوع نقض')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('severity', models.IntegerField(default=1, help_text='شدت نقض', verbose_name='شدت (۱-۵)')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='برطرف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان نقض')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان برطرف\u200cسازی')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_violations', to='trading.trade', verbose_name='ترید مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_violations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نقض انضباطی',
                'verbose_name_plural': 'نقض\u200cهای انضباطی',
                'db_table': 'trading_discipline_violation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='trading_dis_user_id_99e5f4_idx'), models.Index(fields=['user', 'violation_type'], name='trading_dis_user_id_038638_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_plan', models.BooleanField(default=True, verbose_name='از برنامه پیروی کردی؟')),
                ('learned_lesson', models.TextField(blank=True, verbose_name='چه آموختی؟')),
                ('emotion_after', models.CharField(blank=True, max_length=50, verbose_name='احساس پس از معامله')),
                ('improvement_note', models.TextField(blank=True, verbose_name='نکته بهبود')),
                ('quality_score', models.IntegerField(default=3, verbose_name='امتیاز کیفیت بازتاب (۱-۵)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='trading.trade', verbose_name='ترید')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازتاب',
                'verbose_name_plural': 'بازتاب\u200cها',
                'db_table': 'trading_reflection',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='trading_ref_user_id_4435c8_idx'), models.Index(fields=['trade'], name='trading_ref_trade_i_2600ba_idx')],
            },
        ),
    ]
