# Generated by Django 5.2.16 on 2026-08-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_disciplinesettings_dailydisciplinestate_dailyhabit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام بروکر')),
                ('category', models.CharField(choices=[('international_fx', 'بروکرهای بین\u200cالمللی فارکس و CFD'), ('international_crypto', 'صرافی\u200cهای ارز دیجیتال بین\u200cالمللی'), ('iranian_crypto', 'صرافی\u200cهای ارز دیجیتال داخلی'), ('iranian_stock', 'کارگزاری\u200cهای بورس داخلی')], default='international_fx', max_length=30, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order_index', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'بروکر',
                'verbose_name_plural': 'بروکرها',
                'ordering': ['category', 'order_index', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='trading_bro_categor_938d96_idx'), models.Index(fields=['name'], name='trading_bro_name_23d041_idx')],
            },
        ),
        migrations.AddField(
            model_name='trade',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trading.broker', verbose_name='بروکر/کارگزار'),
        ),
    ]
