# Generated by Django 5.2.16 on 2026-08-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_broker_trade_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_time',
            field=models.TimeField(blank=True, help_text='ساعت، دقیقه و ثانیه معامله (اختیاری، پیش\u200cفرض 00:00:00)', null=True, verbose_name='زمان معامله'),
        ),
    ]
