# Generated by Django 5.2.16 on 2026-09-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_trade_trade_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trade_time',
        ),
    ]
