# Generated by Django 5.2.16 on 2026-07-24 07:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='شماره تلفن')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مدیر')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد تایید')),
                ('verification_expiry', models.DateTimeField(blank=True, null=True, verbose_name='انقضای کد تایید')),
                ('login_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='توکن ورود')),
                ('login_token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='انقضای توکن ورود')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='شماره نسخه')),
                ('release_date', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('release_notes', models.TextField(verbose_name='یادداشت\u200cهای انتشار')),
                ('is_current', models.BooleanField(default=False, verbose_name='نسخه جاری')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'نسخه نرم\u200cافزار',
                'verbose_name_plural': 'نسخه\u200cهای نرم\u200cافزار',
                'db_table': 'app_versions',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_key', models.CharField(blank=True, max_length=100, verbose_name='کلید پیام')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'پیام سیستم',
                'verbose_name_plural': 'پیام\u200cهای سیستم',
                'db_table': 'system_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100, unique=True, verbose_name='کلید تنظیم')),
                ('setting_value', models.TextField(blank=True, null=True, verbose_name='مقدار تنظیم')),
                ('setting_type', models.CharField(default='string', max_length=20, verbose_name='نوع تنظیم')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_editable', models.BooleanField(default=True, verbose_name='قابل ویرایش')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیم سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
                'db_table': 'system_settings',
                'ordering': ['setting_key'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'ورود'), ('logout', 'خروج'), ('trade_create', 'ایجاد ترید'), ('trade_update', 'ویرایش ترید'), ('trade_delete', 'حذف ترید'), ('profile_update', 'ویرایش پروفایل'), ('subscription_purchase', 'خرید اشتراک'), ('message_send', 'ارسال پیام'), ('report_view', 'مشاهده گزارش'), ('export', 'خروجی گرفتن')], max_length=30, verbose_name='نوع اقدام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='مرورگر')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت',
                'db_table': 'user_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_activi_user_id_98e74d_idx'), models.Index(fields=['action_type'], name='user_activi_action__4357b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='مرورگر')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ورود')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('session_duration', models.IntegerField(default=0, verbose_name='مدت جلسه (ثانیه)')),
                ('is_successful', models.BooleanField(default=True, verbose_name='موفق')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ ورود',
                'verbose_name_plural': 'لاگ\u200cهای ورود',
                'db_table': 'user_login_logs',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'login_time'], name='user_login__user_id_34f1ef_idx'), models.Index(fields=['is_successful'], name='user_login__is_succ_42ca39_idx')],
            },
        ),
    ]
