# Generated by Django 5.2.16 on 2026-08-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_type',
            field=models.CharField(choices=[('string', 'رشته'), ('integer', 'عدد صحیح'), ('boolean', 'بولی'), ('text', 'متن طولانی'), ('float', 'عدد اعشاری'), ('json', 'JSON')], default='string', max_length=20, verbose_name='نوع تنظیم'),
        ),
    ]
