# Generated by Django 5.2.16 on 2026-08-13 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('view', 'مشاهده'), ('export', 'خروجی'), ('send_sms', 'ارسال پیامک'), ('extend_subscription', 'تمدید اشتراک'), ('toggle_user', 'تغییر وضعیت کاربر')], max_length=20, verbose_name='نوع اقدام')),
                ('target_model', models.CharField(max_length=50, verbose_name='مدل هدف')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='آیدی هدف')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='آی\u200cپی')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'لاگ اقدام ادمین',
                'verbose_name_plural': 'لاگ\u200cهای اقدام ادمین',
                'ordering': ['-created_at'],
            },
        ),
    ]
